server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mqdemo?serverTimezone=GMT%2B8&autoR&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
# rabbitmq
  rabbitmq:
    host: 192.168.235.50
    port: 5672
    virtual-host: study
    username: admin
    password: 123456
    # 开启confirms回调 P -> Exchange
    publisher-confirms: true
    # 开启returnedMessage回调 Exchange -> Queue
    publisher-returns: true
    # 设置手动确认(ack) Queue -> C
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  mail:
    host: smtp.163.com
    username: *
    password: *
    from: *
    title: "新消息"
    content: "成功注册"
